# Mod05 NumPy Basic Operations

# Operations

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.<br>
Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs.

## Basic Operations

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.<br>
The standard addition, subtraction, multiplication, and division can all be used.

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.19.1'

In [3]:
pd.__version__

'1.0.5'

In [4]:
ar=np.arange(0,7)*5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [5]:
ar=np.arange(5) ** 4 ; ar

array([  0,   1,  16,  81, 256])

In [6]:
ar ** 0.5     # 以copy的方式 原稿沒變

array([ 0.,  1.,  4.,  9., 16.])

In [13]:
ar

array([  0,   1,  16,  81, 256])

In [8]:
ar=3+np.arange(0, 30,3); ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [15]:
ar2=np.arange(1,11); ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
ar+ar2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [17]:
ar/ar2

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [18]:
ar**ar2     #如果是32 位元, 30^10 會overflow

array([              3,              36,             729,           20736,
                759375,        34012224,      1801088541,    110075314176,
         7625597484987, 590490000000000])

In [24]:
np.array((10**30,11**30),dtype ='float32')

array([1.0000000e+30, 1.7449402e+31], dtype=float32)

In [27]:
np.array((10**30,11**30),dtype ='int16')   #overflow

OverflowError: Python int too large to convert to C long

<b>Array multiplication is element wise</b><br>

In [28]:
ar=np.array([[1,1],[1,1]]); ar

array([[1, 1],
       [1, 1]])

In [29]:
ar2=np.array([[2,2],[2,2]]); ar2

array([[2, 2],
       [2, 2]])

In [30]:
ar*ar2

array([[2, 2],
       [2, 2]])

In [31]:
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

In [35]:
ar3=np.array([[1,1],[1,1],[1,1]]); ar3

array([[1, 1],
       [1, 1],
       [1, 1]])

In [36]:
ar4=np.array([[1,1,3],[1,1,4]]); ar4

array([[1, 1, 3],
       [1, 1, 4]])

In [37]:
ar3.dot(ar4)

array([[2, 2, 7],
       [2, 2, 7],
       [2, 2, 7]])

<b>Comparison and logical operations are also elememt-wise</b>

In [38]:
ar=np.arange(1,5); ar

array([1, 2, 3, 4])

In [44]:
# ar2=np.arange(5,1); ar2

In [43]:
ar2=np.arange(5,1,-1); ar2

array([5, 4, 3, 2])

In [40]:
ar < ar2

array([ True,  True, False, False])

In [41]:
ar != ar2

array([ True,  True, False,  True])

In [46]:
l1 = np.array([True,False,True,False])
l2 = np.array([False,False,True, False])

In [51]:
np.logical_and(l1,l2)

array([False, False,  True, False])

In [52]:
np.logical_or(l1,l2)

array([ True, False,  True, False])

In [53]:
np.logical_xor(l1,l2)

array([ True, False, False, False])

In [54]:
np.logical_not(l2)

array([ True,  True, False,  True])

In [48]:
True xor False # python 沒有

SyntaxError: invalid syntax (<ipython-input-48-15f417f402f5>, line 1)

In [50]:
l1 and l2  # numpu 無法用logical operators

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<b>For element-wise operations, the 2 arrays must be the same shape else an error results</b>

In [55]:
ar=np.arange(0,6); ar

array([0, 1, 2, 3, 4, 5])

In [56]:
ar2=np.arange(0,8); ar2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
ar*ar2

ValueError: operands could not be broadcast together with shapes (6,) (8,) 

<b>NumPy arrays can be transposed</b>

In [58]:
ar=np.array([[1,2,3],[4,5,6]]); ar

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
ar.shape

(2, 3)

In [64]:
a = ar.T ;a  #copy, 屬性比較transpose(function)快  

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
a.shape

(3, 2)

In [65]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
ar.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [68]:
arr3 = np.arange(12) ; arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
arr3 = arr3.reshape((4,3));arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
arr3 = arr3.reshape(4,3);arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<b>Compare arrays not element-wise but array-wise</b><br>
Suppose we wish to compare arrays not element-wise, but array-wise. We could
achieve this as follows by using the np.array_equal operator:

In [ ]:
ar=np.arange(0,6)
ar2=np.array([0,1,2,3,4,5])
np.array_equal(ar, ar2)

Here, we see that a single Boolean value is returned instead of a Boolean array. The
value is True only if all the corresponding elements in the two arrays match. The
preceding expression is equivalent to the following:

In [ ]:
np.all(ar==ar2)

## Reduction Operations
Operators such as np.sum and np.prod perform reduces on arrays; that is, they
combine several elements into a single value:

In [75]:
ar=np.arange(1,5); ar

array([1, 2, 3, 4])

In [77]:
ar.prod()    #相乘 1*2*3*4

24

specify whether the reduction operator to be applied row-wise or column-wise

In [78]:
ar=np.array([np.arange(1,6),np.arange(1,6)]); ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [89]:
ar1 = ar.prod() ; ar1

3628800

In [79]:
#Columns  軸為0 縱向  1*1  2*2  3*3  4*4  5*5 
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [80]:
#Rows  軸為1 橫向 1*2*3*4*5   1*2*3*4*5 
np.prod(ar,axis=1)

array([120, 120])

not specifying an axis results in the operation being applied to all elements of the array

In [105]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]); ar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [106]:
ar.sum()

54

In [107]:
ar.sum(axis =1)

array([ 9, 18, 27])

In [108]:
np.median(ar)  

6.0

In [113]:
np.median(ar, axis=1)  #如果數值是偶數，會相加除以2, 所以以浮點表示, 

array([3., 6., 9.])

In [115]:
arr = np.random.randn(5, 4); arr

array([[-0.27630324, -0.22441348, -0.17058595,  1.27590208],
       [ 1.09473113,  0.72420051,  0.75351142, -0.31049815],
       [ 0.15560087, -0.13175396, -0.65008069,  0.77601863],
       [ 1.08538341,  1.28691496,  0.85479136,  1.46264712],
       [-1.12164777, -0.99127339, -0.61124756, -0.3977282 ]])

In [116]:
rand = np.random.RandomState(42)
arr = rand.randn(5,4); arr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783, -0.56228753],
       [-1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [117]:
arr.mean()

-0.17129856144182892

In [118]:
arr.mean(axis=0)

array([-0.19555649, -0.28577483, -0.17389165, -0.02997128])

In [119]:
arr.mean(axis=1)

array([ 0.63229206,  0.4695893 , -0.21401545, -0.98963083, -0.75472789])

## Lab

<b>使用 NumPy 版的三元運算子 x if c else y，試著將兩個陣列相同位置的元素較大者取出</b>

In [ ]:
xarr = np.array([1.1, 3.2, 1.3, 1.4, 5.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([False, True, False, False, True])

<b>有一個二維陣列 data，試著:
* 求 data 的平均值
* 求每一列的平均值
* 求每一列的平均值，並設定每個元素的權重為 0.25 與 0.75
</b>

In [ ]:
data = np.arange(6).reshape((3,2))
data