# Mod03 Create NumPy Array

In [62]:
import numpy as np
import pandas as pd

In [5]:
np.__version__

'1.19.1'

In [6]:
pd.__version__

'1.0.5'

## NumPy array creation via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [7]:
ar1 = np.array([0,1,2,3]) # 1 dimensional array

In [8]:
ar2=np.array([[0,3,5],[2,8,7]]) # 2D array

In [12]:
lst = [1,2,3,4]     #lsit 與np array 不同
lst  

[1, 2, 3, 4]

In [9]:
ar1

array([0, 1, 2, 3])

In [10]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [13]:
# shape   numpy的array 是row major  以row為主
ar2.shape

(2, 3)

In [14]:
# ndim
ar2.ndim

2

In [15]:
# dtype   Linux是64位元, windows上是32位元  可以判斷在什麼平台跑, 會影響後面
ar2.dtype

dtype('int64')

In [18]:
#shape
ar1.shape

(4,)

In [17]:
#dtype
ar1.dtype

dtype('int64')

## NumPy array creation via numpy.arange
ndarray.arange is the NumPy version of Python's range function

In [19]:
#ar3=np.arange(12); ar3
ar3=np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# start, end (exclusive)
#ar4=np.arange(3,10,3); ar4
ar4=np.arange(3,10,3)
ar4

array([3, 6, 9])

In [21]:
ar5=np.arange(5,10)
ar5  

array([5, 6, 7, 8, 9])

In [23]:
ar5.dtype

dtype('int64')

In [22]:
type(ar5)  

numpy.ndarray

## NumPy datatypes
Specify the type of contents of a numeric array by using the dtype parameter

In [27]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3]);   #沒給dtype會是int格式
ar

array([ 2, -1,  6,  3])

In [28]:
ar.dtype

dtype('int64')

In [24]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype=np.float);   #Numpy style  預設為 float64
ar

array([ 2., -1.,  6.,  3.])

In [25]:
#ar=np.array([2,-1,6,3],dtype='float'); ar
ar=np.array([2,-1,6,3],dtype='float');   #C style
ar

array([ 2., -1.,  6.,  3.])

In [26]:
ar.dtype

dtype('float64')

### NumPy is faster than list

In [33]:
%%timeit
lst =[]
for i in range(2,1001,2):
    lst.append(i)
lst

17.4 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [34]:
%%timeit
arr = np.arange(2,1001,2)
arr

710 ns ± 6.39 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [36]:
ar=np.array([2,4,6,8]); ar.dtype

dtype('int64')

In [37]:
ar=np.array([2.,4,6,8]); ar.dtype

dtype('float64')

In [38]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); sar.dtype

dtype('<U9')

In [39]:
bar=np.array([True, False, True]); bar.dtype

dtype('bool')

In [42]:
f_ar = np.array([3,-2,8.98])
f_ar

array([ 3.  , -2.  ,  8.98])

In [50]:
f_ar.astype(int)   #沒有改變原本的陣列

array([ 3, -2,  8])

## NumPy array creation via numpy.linspace
ndarray.linspace generates linear evenly spaced elements between the start and the end

In [51]:
# args - start element,end element, number of elements
#ar6=np.linspace(0,2.0/3,4); ar5
ar6=np.linspace(0,2.0/3,4)
ar6

array([0.        , 0.22222222, 0.44444444, 0.66666667])

## NumPy array via various other functions
These functions include numpy.zeros, numpy.ones, numpy.eye, nrandom.rand,
numpy.random.randn, and numpy.empty

### numpy.ones

In [52]:
# Produces 2x3x2 array of 1's.
ar7=np.ones((2,3,2)); ar7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.zeros

In [53]:
# Produce 4x2 array of zeros.  #等於C語言的 calloc()，會清空裡面的值
ar8=np.zeros((4,2)); ar8

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.eye

In [54]:
# Produces identity matrix
ar9 = np.eye(3); ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.empty

In [55]:
ar13=np.empty((3,2)); ar13   #未初始化, 原本如果記憶體有值也會使用, 要注意!!  等於C的malloc()  

array([[2.11508475e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

### numpy.random.rand

In [56]:
# Using the rand, randn functions
# rand(m) produces an array of the given shape 
# with uniformly distributed random numbers over [0,1)  randn 設定由0-1分配的亂數
np.random.seed(200) # Set seed   設定固定值, 大家看到的都會相同
ar11=np.random.rand(3); ar11

array([0.94763226, 0.22654742, 0.59442014])

In [57]:
# randn(m) produces m normally distributed (Gaussian) random numbers
ar12=np.random.randn(5); ar12

array([ 1.4983231 , -0.40666493, -0.09376948,  0.87472083,  0.83141749])

In [59]:
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## Lab

<b> 利用 arange() 建立一個 array([11, 14, 17, 20]) 的陣列 <b>

In [79]:
arr1 = np.arange(11,21,3)
arr1

array([11, 14, 17, 20])

In [82]:
arr3 = np.array([11,14,17,20]); arr3

array([11, 14, 17, 20])

<b>透過 ```arr = np.array([[1, 2], [3, 4]]) ```
建立如下的陣列
```
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])
```
</b>


In [77]:
arr2 = np.array([[1,2,1],[3,4,3]])
arr2

array([[1, 2, 1],
       [3, 4, 3]])